image: tk120404/node:22.2.0      

variables:
  GIT_STRATEGY: fetch

prod_build:
  tags:
    - lucy-master
  stage: build
  environment:
    name: prod
  script:
    - npm install
    - npm run build
    - echo $prodEnvKey | base64 -d > prodEnvKey.pem
    - chmod 400 prodEnvKey.pem
    - zip -qq -r $CI_JOB_ID.zip ./ -x prodEnvKey.pem
    - scp -i prodEnvKey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_JOB_ID.zip ubuntu@prod-api.instavans.com:/home/ubuntu/milkyway/packages/juggernaut-$CI_JOB_ID.zip
    - ssh -t -t -i prodEnvKey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@prod-api.instavans.com << EOF
    - rm -rf /home/ubuntu/milkyway/juggernaut/*
    - cd /home/ubuntu/milkyway/juggernaut
    - cp /home/ubuntu/milkyway/packages/juggernaut-$CI_JOB_ID.zip .
    - unzip -qq -o juggernaut-$CI_JOB_ID.zip
    - rm -rf juggernaut-$CI_JOB_ID.zip
    - ls
    - rm /home/ubuntu/milkyway/packages/juggernaut-$CI_JOB_ID.zip
    # - rm -rf node_modules
    - nvm use v22
    - npm ci
    - nvm use default
    - pm2 reload juggernaut
    - exit
  when: manual
