export const environment = {
    API_URL: 'https://dev-api.instavans.com/api/thor/v1/',
    API_URL_DASHBOARD: 'https://dev-api.instavans.com/api/thanos/v1/',
    API_URL_DASHBOARD2: 'https://dev-api.instavans.com/api/thanos/v2/',
    API_URL_DASHBOARD3: 'https://dev-api.instavans.com/api/thanos2/v1/',
    GOOGLE_MAP_API: 'https://www.google.com/',
    BASE_URL:'https://smartdashbaord.instavans.com/',
    DEV_ETMS:'https://etms.instavans.com/',
    PROD_SMART:'https://smartshipper.instavans.com/',
    TRACKER_URL: 'https://tracker.instavans.com/track/',
    TRIP_TRACKER: 'https://etms-tracker.instavans.com/track/',
    TRACKER_URL_PREFIX: "https://etms-tracker.instavans.com/track/",
    API_URL_NEW_1: 'https://dev-api.instavans.com/api/thor/',
    API_URL_NEW_2: 'https://dev-api.instavans.com/api/thor/v2/',
}