import {
    User,
    IndianRupee,
    CheckCircle,
    Clock,
    FileSearch,
    AlertTriangle,
    FileWarning,
    CalendarX2,
    PackageX,
    Sigma,
    Truck,
    MapPin,
    GitPullRequestClosed,
    XCircle,
    PackageCheck,
    Loader2,
    AlertCircle,
    FileCheck,
    Database,
    Target,
    ReceiptIndianRupee,
  } from "lucide-react";
  
  export const iconMap: { [key: string]: React.ElementType } = {
    User,
    IndianRupee,
    CheckCircle,
    Clock,
    FileSearch,
    AlertTriangle,
    FileWarning,
    CalendarX2,
    PackageX,
    Sigma,
    Truck,
    MapPin,
    GitPullRequestClosed,
    XCircle,
    PackageCheck,
    Loader2,
    AlertCircle,
    FileCheck,
    Database, 
    Target,   
    ReceiptIndianRupee,
  
    default: User,
  };
  